# =============================================================================
# BASE CONFIGURATION
# =============================================================================

version: "3.7"

# =============================================================================
# SERVICES
# =============================================================================

services:

# =============================================================================
# MANAGER
# =============================================================================

  manager:
    container_name: ${CONTAINER_NAME}
    env_file: ./.env
    build:
      context: ./${PATH_DOCKERFILE}
      dockerfile: Dockerfile
    entrypoint: >
      /bin/sh -c "
        set -e
        ./docker.sh
        /bin/bash || exit 0
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "https://raw.githubusercontent.com/lpmatos/kubeclt-context-manager/master/install.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    networks:
      - manager

# =============================================================================
# NETWORKS
# =============================================================================

networks:
  manager:
